---
loader: taskgraph.loader.transform:loader

transforms:
  - src.transforms:taskcluster_images
  - taskgraph.transforms.job:transforms
  - taskgraph.transforms.task:transforms

job-defaults:
  worker-type: ci
  run:
    using: bare
  worker:
    max-run-time: 600
    docker-image: {taskcluster: 'node-and-go'}

jobs:
  tests:
    description: taskcluster package meta tests
    run:
      install: yarn install
      command: "set -o pipefail && yarn test:meta | cat"
